In [1]:
import pandas as pd
import requests

import openmeteo_requests
import requests_cache
from retry_requests import retry
from datetime import date, timedelta

### Get new Meteo

In [2]:
cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

URL_METEO = "https://archive-api.open-meteo.com/v1/archive"
today = date.today().strftime('%Y-%m-%d')
params = {
	"latitude": 40.4165,
	"longitude": -3.7026,
	"hourly": [
        "wind_speed_10m",
        "wind_gusts_10m",
        "relative_humidity_2m",
        "dew_point_2m",
        "vapour_pressure_deficit",
        "cloud_cover",
        "soil_temperature_0_to_7cm",
        "soil_moisture_0_to_7cm",
    ],
    "daily": [
        "temperature_2m_mean",
        "wind_direction_10m_dominant",
        "et0_fao_evapotranspiration",
        "shortwave_radiation_sum",
        "temperature_2m_max",
        "temperature_2m_min",
        "rain_sum"
    ],
	"start_date": "2026-01-01",
    "end_date": today,
    "timezone": "Europe/Madrid"
}
responses = openmeteo.weather_api(URL_METEO, params=params)

response = responses[0]
hourly = response.Hourly()
hourly_data = {
    "date": pd.date_range(
        start = pd.to_datetime(hourly.Time(), unit = "s", utc = True),
        end =  pd.to_datetime(hourly.TimeEnd(), unit = "s", utc = True),
        freq = pd.Timedelta(seconds = hourly.Interval()),
        inclusive = "left"
    ),
    "wind_speed_10m (km/h)": hourly.Variables(0).ValuesAsNumpy(),
    "wind_gusts_10m (km/h)": hourly.Variables(1).ValuesAsNumpy(),
    "relative_humidity_2m (%)": hourly.Variables(2).ValuesAsNumpy(),
    "dew_point_2m (°C)": hourly.Variables(3).ValuesAsNumpy(),
    "vapour_pressure_deficit (kPa)": hourly.Variables(4).ValuesAsNumpy(),
    "cloud_cover (%)": hourly.Variables(5).ValuesAsNumpy(),
    "soil_temperature_0_to_7cm (°C)": hourly.Variables(6).ValuesAsNumpy(),
    "soil_moisture_0_to_7cm (m³/m³)": hourly.Variables(7).ValuesAsNumpy()
}
hourly_dataframe = pd.DataFrame(data = hourly_data)

daily = response.Daily()
daily_data = {
    "date": pd.date_range(
        start = pd.to_datetime(daily.Time(), unit = "s", utc = True),
        end = pd.to_datetime(daily.TimeEnd(), unit = "s", utc = True),
        freq = pd.Timedelta(seconds = daily.Interval()),
        inclusive = "left"
    ),
    "temp_mean": daily.Variables(0).ValuesAsNumpy(),
    "wind_dir_dominant": daily.Variables(1).ValuesAsNumpy(),
    "evapotranspiration": daily.Variables(2).ValuesAsNumpy(),
    "radiation_sum": daily.Variables(3).ValuesAsNumpy(),
    "max_temp": daily.Variables(4).ValuesAsNumpy(),
    "min_temp": daily.Variables(5).ValuesAsNumpy(),
    "total_rain": daily.Variables(6).ValuesAsNumpy()
}
df_diario = pd.DataFrame(data = daily_data)

hourly_dataframe['fecha'] = pd.to_datetime(hourly_dataframe['date']).dt.date
df_meteo_pred = hourly_dataframe.groupby('fecha').mean(numeric_only=True).reset_index()
df_meteo_pred['fecha'] = pd.to_datetime(df_meteo_pred['fecha']).dt.tz_localize(None)
df_diario['date'] = pd.to_datetime(df_diario['date']).dt.tz_localize(None).dt.normalize()
df_final = pd.merge(df_meteo_pred, df_diario, left_on='fecha', right_on='date', how='left')
df_nuevos_meteo = df_final.drop(columns=['date'])
df_nuevos_meteo

,fecha,wind_speed_10m (km/h),wind_gusts_10m (km/h),relative_humidity_2m (%),dew_point_2m (°C),vapour_pressure_deficit (kPa),cloud_cover (%),soil_temperature_0_to_7cm (°C),soil_moisture_0_to_7cm (m³/m³),temp_mean,wind_dir_dominant,evapotranspiration,radiation_sum,max_temp,min_temp,total_rain
0,2025-12-31,0.810000,4.500000,89.282104,0.100000,0.074171,100.000000,2.700000,0.159000,1.075000,21.888302,0.496331,5.000000,3.150000,-1.500000,0.1
1,2026-01-01,3.856120,9.750000,91.673927,-0.029167,0.056940,98.375000,1.060417,0.160167,5.947916,20.165291,0.613425,4.590000,9.750000,3.050000,0.7
2,2026-01-02,6.514946,14.864999,90.102448,4.725000,0.099137,99.666664,5.689583,0.179125,8.333333,26.387047,0.767176,5.510000,12.150000,6.150000,0.2
3,2026-01-03,7.491186,17.309999,86.490654,6.187500,0.160529,95.791664,7.681250,0.201292,7.991666,34.986076,0.889832,6.830000,11.550000,5.700000,5.8
4,2026-01-04,7.171152,18.105000,86.508392,5.506250,0.153167,82.041664,8.112500,0.218958,2.479167,32.204098,1.147204,8.610000,5.750000,0.200000,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,2026-05-31,8.350652,24.164999,26.199142,4.485417,3.043680,53.541668,31.985418,0.077417,27.772917,286.711487,8.099844,29.549999,34.299999,20.299999,0.0
152,2026-06-01,11.083806,30.974998,31.121138,7.520833,2.811308,41.125000,31.662500,0.077333,26.399996,298.174286,7.538097,28.910000,30.200001,21.650000,0.0
153,2026-06-02,9.950861,27.644999,28.910395,5.804167,2.478018,51.416668,30.670832,0.077292,24.270834,307.681030,6.788065,28.920000,32.799999,16.400000,0.0
154,2026-06-03,7.648832,23.894999,37.286407,7.566667,2.147956,21.208334,29.306250,0.077500,24.043749,284.558472,7.060052,29.080000,28.450001,19.400000,0.0
155,2026-06-04,11.298574,30.616364,34.787758,6.177273,2.024299,19.863636,28.829546,0.077364,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get new Contaminantes

In [3]:
URL_CONTAMINANTES = "https://datos.madrid.es/egob/catalogo/300755-12751586-calidad-aire-tiempo-real-acumula.json"

response = requests.get(URL_CONTAMINANTES)
nuevos_datos = response.json()
df_nuevos = pd.DataFrame(nuevos_datos['data'] if 'data' in nuevos_datos else nuevos_datos)
df_nuevos = pd.DataFrame(df_nuevos['records'].tolist())

df_nuevos_cont = df_nuevos[df_nuevos['ESTACION'] == "8"].copy()

magnitude_map = {
    '1': 'SO2 (ug/m3)', '6': 'CO (mg/m3)', '7': 'NO (ug/m3)', '8': 'NO2 (ug/m3)',
    '9': 'PM2.5 (ug/m3)', '10': 'PM10 (ug/m3)', '12': 'NOx (ug/m3)', '14': 'O3 (ug/m3)',
    '20': 'Tolueno (ug/m3)', '30': 'Benceno (ug/m3)', '42': 'HCT (mg/m3)', '44': 'HCNM (mg/m3)'
}

d_cols = [f'H{i:02d}' for i in range(1, 25)]
v_cols = [f'V{i:02d}' for i in range(1, 25)]

rows = []
for idx, row in df_nuevos_cont.iterrows():
    for d, v in zip(d_cols, v_cols):
        if v in row and row[v] == 'V':
            val = str(row[d]).replace(',', '.')
            hour_num = int(d[1:])
            rows.append({
                'ano': row['ANO'], 
                'mes': row['MES'], 
                'dia': row['DIA'],
                'hora': hour_num,
                'magnitud': row['MAGNITUD'],
                'valor': pd.to_numeric(val, errors='coerce')
            })

df_melted = pd.DataFrame(rows)
df_melted['fecha'] = pd.to_datetime(df_melted[['ano', 'mes', 'dia']].rename(
    columns={'ano': 'year', 'mes': 'month', 'dia': 'day'}), errors='coerce')
df_melted = df_melted.dropna(subset=['fecha'])

df_diario = df_melted.groupby(['ano', 'mes', 'dia', 'magnitud'], as_index=False)['valor'].mean()
df_diario['fecha'] = pd.to_datetime(df_diario[['ano', 'mes', 'dia']].rename(
    columns={'ano': 'year', 'mes': 'month', 'dia': 'day'}
)).dt.date

df_diario['magnitud'] = df_diario['magnitud'].astype(str).map(magnitude_map)
df_nuevos_cont = df_diario.pivot_table(
    index='fecha', 
    columns='magnitud', 
    values='valor', 
    aggfunc='mean'
).reset_index()
df_nuevos_cont = df_nuevos_cont.round(1)
df_nuevos_cont.columns.name = None
df_nuevos_cont['fecha'] = pd.to_datetime(df_nuevos_cont['fecha'])

### Meteo and contaminantes Predictions

In [4]:
URL_METEO_FORECAST = "https://api.open-meteo.com/v1/forecast"
today = date.today()
start = today.strftime('%Y-%m-%d')
end = (today + timedelta(days=2)).strftime('%Y-%m-%d')

params_meteo = {
    "latitude": 40.4165,
    "longitude": -3.7026,
    "hourly": [
        "wind_speed_10m",
        "wind_gusts_10m",
        "relative_humidity_2m",
        "dew_point_2m",
        "vapour_pressure_deficit",
        "cloud_cover",
        "soil_temperature_0_to_7cm",
        "soil_moisture_0_to_7cm",
    ],
    "daily": [
        "temperature_2m_mean",
        "wind_direction_10m_dominant",
        "et0_fao_evapotranspiration",
        "shortwave_radiation_sum",
        "temperature_2m_max",
        "temperature_2m_min",
        "rain_sum"
    ],
    "start_date": start,
    "end_date": end,
    "timezone": "Europe/Madrid"
}
responses = openmeteo.weather_api(URL_METEO_FORECAST, params=params_meteo)

response = responses[0]
hourly = response.Hourly()
hourly_data = {
    "date": pd.date_range(
        start = pd.to_datetime(hourly.Time(), unit = "s", utc = True),
        end =  pd.to_datetime(hourly.TimeEnd(), unit = "s", utc = True),
        freq = pd.Timedelta(seconds = hourly.Interval()),
        inclusive = "left"
    ),
    "wind_speed_10m (km/h)": hourly.Variables(0).ValuesAsNumpy(),
    "wind_gusts_10m (km/h)": hourly.Variables(1).ValuesAsNumpy(),
    "relative_humidity_2m (%)": hourly.Variables(2).ValuesAsNumpy(),
    "dew_point_2m (°C)": hourly.Variables(3).ValuesAsNumpy(),
    "vapour_pressure_deficit (kPa)": hourly.Variables(4).ValuesAsNumpy(),
    "cloud_cover (%)": hourly.Variables(5).ValuesAsNumpy(),
    "soil_temperature_0_to_7cm (°C)": hourly.Variables(6).ValuesAsNumpy(),
    "soil_moisture_0_to_7cm (m³/m³)": hourly.Variables(7).ValuesAsNumpy()
}
hourly_dataframe = pd.DataFrame(data = hourly_data)

daily = response.Daily()
daily_data = {
    "date": pd.date_range(
        start = pd.to_datetime(daily.Time(), unit = "s", utc = True),
        end = pd.to_datetime(daily.TimeEnd(), unit = "s", utc = True),
        freq = pd.Timedelta(seconds = daily.Interval()),
        inclusive = "left"
    ),
    "temp_mean": daily.Variables(0).ValuesAsNumpy(),
    "wind_dir_dominant": daily.Variables(1).ValuesAsNumpy(),
    "evapotranspiration": daily.Variables(2).ValuesAsNumpy(),
    "radiation_sum": daily.Variables(3).ValuesAsNumpy(),
    "max_temp": daily.Variables(4).ValuesAsNumpy(),
    "min_temp": daily.Variables(5).ValuesAsNumpy(),
    "total_rain": daily.Variables(6).ValuesAsNumpy()
}
df_diario = pd.DataFrame(data = daily_data)

hourly_dataframe['date'] = pd.to_datetime(hourly_dataframe['date']).dt.tz_convert('Europe/Madrid')
hourly_dataframe['fecha'] = hourly_dataframe['date'].dt.date

df_diario['date_madrid'] = pd.to_datetime(df_diario['date']).dt.tz_convert('Europe/Madrid').dt.date
df_meteo_pred_group = hourly_dataframe.groupby('fecha').mean(numeric_only=True).reset_index()

df_meteo_pred = pd.merge(
    df_meteo_pred_group, 
    df_diario, 
    left_on='fecha', 
    right_on='date_madrid', 
    how='right' 
)

df_meteo_pred['fecha'] = pd.to_datetime(df_meteo_pred['fecha'])
df_meteo_pred = df_meteo_pred.drop(columns=['date', 'date_madrid']).ffill()

df_meteo_pred

,fecha,wind_speed_10m (km/h),wind_gusts_10m (km/h),relative_humidity_2m (%),dew_point_2m (°C),vapour_pressure_deficit (kPa),cloud_cover (%),soil_temperature_0_to_7cm (°C),soil_moisture_0_to_7cm (m³/m³),temp_mean,wind_dir_dominant,evapotranspiration,radiation_sum,max_temp,min_temp,total_rain
0,2026-06-04,8.953166,25.094999,38.916668,7.623920,1.850176,37.625,28.893751,0.077333,23.417166,293.650482,6.506117,28.65,27.963001,18.963001,0.0
1,2026-06-05,9.692378,27.539999,45.666668,7.720994,1.487554,67.625,26.841667,0.077458,20.746334,24.595760,6.070198,27.91,27.313000,13.763000,0.0
2,2026-06-06,5.470241,16.769999,32.625000,5.431456,2.092194,42.875,28.610418,0.077292,23.610916,251.681152,6.389425,30.15,29.613001,17.463001,0.0

In [ ]:
url = "https://air-quality-api.open-meteo.com/v1/air-quality"
params = {
	"latitude": 40.4165,
	"longitude": -3.7026,
	"hourly": ["pm10", "pm2_5", "carbon_monoxide", "nitrogen_dioxide", "sulphur_dioxide", "ozone"],
	"forecast_days": 3,
}
responses = openmeteo.weather_api(url, params=params)

response = responses[0]
hourly = response.Hourly()
hourly_data = {
    "date": pd.date_range(
		start = pd.to_datetime(hourly.Time(), unit = "s", utc = True),
		end =  pd.to_datetime(hourly.TimeEnd(), unit = "s", utc = True),
		freq = pd.Timedelta(seconds = hourly.Interval()),
		inclusive = "left"
	),
    "PM10 (ug/m3)": hourly.Variables(0).ValuesAsNumpy(),
	"PM2.5 (ug/m3)": hourly.Variables(1).ValuesAsNumpy(),
	"CO (mg/m3)": hourly.Variables(2).ValuesAsNumpy()/1000, # De µg/m3 a mg/m3
	"NO2 (ug/m3)": hourly.Variables(3).ValuesAsNumpy(),
	"SO2 (ug/m3)": hourly.Variables(4).ValuesAsNumpy(),
	"O3 (ug/m3)": hourly.Variables(5).ValuesAsNumpy()

}
hourly_dataframe = pd.DataFrame(data = hourly_data)

hourly_dataframe['fecha'] = pd.to_datetime(hourly_dataframe['date']).dt.date
df_contaminantes_pred = hourly_dataframe.groupby('fecha').mean(numeric_only=True).reset_index()
df_contaminantes_pred['fecha'] = pd.to_datetime(df_contaminantes_pred['fecha'])
df_contaminantes_pred = df_contaminantes_pred.round(1)
df_contaminantes_pred

,fecha,PM10 (ug/m3),PM2.5 (ug/m3),CO (mg/m3),NO2 (ug/m3),SO2 (ug/m3),O3 (ug/m3)
0,2026-06-04,11.1,6.3,0.1,7.0,0.6,56.900002
1,2026-06-05,7.1,4.4,0.1,6.8,0.7,74.800003
2,2026-06-06,10.4,5.5,0.1,8.6,0.9,67.800003

### Get new Polen and MIX

In [ ]:
URL_POLEN = "https://datos.comunidad.madrid/catalogo/dataset/e608aace-3593-43a3-8c91-02332137fa83/resource/db5e3952-57f5-40f3-bb1d-906eb17aebb1/download/mediciones_polen.json"

response = requests.get(URL_POLEN)
nuevos_datos = response.json()
df_nuevos = pd.DataFrame(nuevos_datos['data'] if 'data' in nuevos_datos else nuevos_datos)

tipos_polinicos = {
    "Gram": "gramineas",
    "Cupres": "cupresaceas",
    "Olivo": "olivo",
    "Pl": "platano",
    "Urtic": "urticaceas",
    "Queno": "quenopodiaceas"
}

df_pred_completo = pd.merge(df_meteo_pred, df_contaminantes_pred, on='fecha', how='inner')

for inicales, nombre_limpio in tipos_polinicos.items():
    CSV_POLEN = rf"..\my_datasets\datos_{nombre_limpio}.csv"
    df_master = pd.read_csv(CSV_POLEN)
    df_master['fecha'] = pd.to_datetime(df_master['fecha'])

    df_tipo = df_nuevos[df_nuevos['tipo_polinico'].str.contains(inicales, na=False, case=False)]
    df_tipo = df_tipo[df_tipo['captador'] == 'AYTM']
    df_tipo['fecha'] = pd.to_datetime(df_tipo['fecha_lectura'])
    df_polen_nuevos = df_tipo[['fecha', 'granos_de_polen_x_metro_cubico']].rename(
        columns={'granos_de_polen_x_metro_cubico': f'polen_{nombre_limpio}'}
    )

    df_actualizacion_real = pd.merge(df_polen_nuevos, df_nuevos_meteo, on='fecha', how='outer')
    df_actualizacion_real = pd.merge(df_actualizacion_real, df_nuevos_cont, on='fecha', how='outer')

    df_final = pd.concat([df_master, df_actualizacion_real], ignore_index=True)
    df_final = df_final.groupby('fecha', as_index=False).first()
    df_final = df_final.sort_values('fecha')
    df_final = df_final[df_final['fecha'] < pd.Timestamp(today).normalize()]
    fechas_existentes = df_final['fecha'].unique()

    df_solo_predicciones = df_pred_completo[~df_pred_completo['fecha'].isin(fechas_existentes)].copy()
    df_final_con_pred = pd.concat([df_final, df_solo_predicciones], axis=0, ignore_index=True)
    df_final_con_pred = df_final_con_pred.sort_values('fecha')

    df_final_con_pred['isPrediction'] = df_final_con_pred[f'polen_{nombre_limpio}'].isna().astype(int)
    df_final_con_pred.to_csv(CSV_POLEN, index=False)